Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockNesting:
  Exclude:
    - 'interface/*'

Metrics/MethodLength:
  Exclude:
    - 'interface/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'interface/*'

Metrics/AbcSize:
  Exclude:
    - 'interface/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'interface/*'

Metrics/BlockLength:
  Exclude:
    - 'interface/main_interface.rb'

Metrics/ClassLength:
  Exclude:
    - 'interface/*'

Style/ClassVars:
  Exclude:
    - 'train.rb'

Style/GuardClause:
  Exclude:
    - 'accessors.rb'